-- MySQL Script generated by MySQL Workbench
-- 11/14/16 20:29:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema giodis-oms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `giodis-oms` ;

-- -----------------------------------------------------
-- Schema giodis-oms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `giodis-oms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `giodis-oms` ;

-- -----------------------------------------------------
-- Table `giodis-oms`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `giodis-oms`.`customer` ;

CREATE TABLE IF NOT EXISTS `giodis-oms`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `storer_code` VARCHAR(45) NOT NULL,
  `customer_code` VARCHAR(255) NOT NULL,
  `company_name1` VARCHAR(255) NULL,
  `address1` VARCHAR(255) NULL,
  `country1` VARCHAR(255) NULL,
  `region_code1` VARCHAR(255) NULL,
  `contact_first_name1` VARCHAR(255) NULL,
  `contact_last_name1` VARCHAR(255) NULL,
  `contact_phone1` VARCHAR(255) NULL,
  `user_field1` VARCHAR(255) NULL,
  `user_field2` VARCHAR(255) NULL,
  `user_field3` VARCHAR(255) NULL,
  `user_field4` VARCHAR(255) NULL,
  `user_field5` VARCHAR(255) NULL,
  `user_field6` VARCHAR(45) NULL,
  `user_field7` VARCHAR(45) NULL,
  `user_field8` VARCHAR(45) NULL,
  `user_field9` VARCHAR(45) NULL,
  `user_field10` VARCHAR(45) NULL,
  `user_field11` INT ZEROFILL NULL,
  `user_field12` INT ZEROFILL NULL,
  `is_deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Customer';


-- -----------------------------------------------------
-- Table `giodis-oms`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `giodis-oms`.`user` ;

CREATE TABLE IF NOT EXISTS `giodis-oms`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `user_status` VARCHAR(45) NULL,
  `expiry_date` DATE NULL,
  `full_name` VARCHAR(255) NULL,
  `is_deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `giodis-oms`.`connector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `giodis-oms`.`connector` ;

CREATE TABLE IF NOT EXISTS `giodis-oms`.`connector` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(45) NULL,
  `database_name` VARCHAR(45) NULL,
  `project_id` VARCHAR(45) NULL,
  `project_name` VARCHAR(45) NULL,
  `connector_id` VARCHAR(45) NULL,
  `field1` VARCHAR(45) NULL,
  `field2` VARCHAR(45) NULL,
  `field3` VARCHAR(45) NULL,
  `field4` INT NULL,
  `field5` INT NULL,
  `is_deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `giodis-oms`.`user_has_connector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `giodis-oms`.`user_has_connector` ;

CREATE TABLE IF NOT EXISTS `giodis-oms`.`user_has_connector` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `connector_id` INT NOT NULL,
  INDEX `fk_user_has_connector_connector1_idx` (`connector_id` ASC),
  INDEX `fk_user_has_connector_user_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_has_connector_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `giodis-oms`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_connector_connector1`
    FOREIGN KEY (`connector_id`)
    REFERENCES `giodis-oms`.`connector` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `giodis-oms`.`sale_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `giodis-oms`.`sale_order` ;

CREATE TABLE IF NOT EXISTS `giodis-oms`.`sale_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sale_order_no` VARCHAR(45) NOT NULL,
  `storer_code` VARCHAR(45) NOT NULL,
  `customer_id` INT NOT NULL,
  `user_has_connector_id` INT NOT NULL,
  `expected_delivery_date` DATETIME NOT NULL,
  `order_type` VARCHAR(45) NOT NULL,
  `fulfilment_type` VARCHAR(45) NOT NULL,
  `recipient_code` VARCHAR(45) NOT NULL,
  `rec_address1` VARCHAR(45) NOT NULL,
  `rec_address2` VARCHAR(45) NOT NULL,
  `rec_address3` VARCHAR(45) NULL,
  `rec_address4` VARCHAR(45) NULL,
  `rec_country` VARCHAR(45) NULL,
  `user_field1` VARCHAR(45) NULL,
  `user_field2` VARCHAR(45) NULL,
  `user_field3` VARCHAR(45) NULL,
  `user_field4` VARCHAR(45) NULL,
  `user_field5` VARCHAR(45) NULL,
  `user_field6` VARCHAR(45) NULL,
  `user_field7` VARCHAR(45) NULL,
  `user_field8` VARCHAR(45) NULL,
  `user_field9` VARCHAR(45) NULL,
  `user_field10` VARCHAR(45) NULL,
  `user_field11` INT NULL,
  `user_field12` INT NULL,
  `rec_zip` VARCHAR(45) NULL,
  `rec_contact` VARCHAR(45) NULL,
  `rec_remark` VARCHAR(45) NULL,
  `rec_name` VARCHAR(45) NULL,
  `is_deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SalesOrder_customer1_idx` (`customer_id` ASC),
  INDEX `fk_sale_order_user_has_connector1_idx` (`user_has_connector_id` ASC),
  CONSTRAINT `fk_SalesOrder_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `giodis-oms`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_order_user_has_connector1`
    FOREIGN KEY (`user_has_connector_id`)
    REFERENCES `giodis-oms`.`user_has_connector` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `giodis-oms`.`sale_order_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `giodis-oms`.`sale_order_detail` ;

CREATE TABLE IF NOT EXISTS `giodis-oms`.`sale_order_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seq_no` INT NOT NULL,
  `item` VARCHAR(45) NULL,
  `sale_order_id` INT NOT NULL,
  `order_qty` DECIMAL(16,4) NULL,
  `delivery_qty` DECIMAL(16,4) NULL,
  `user_field1` VARCHAR(45) NULL,
  `user_field2` VARCHAR(45) NULL,
  `user_field3` VARCHAR(45) NULL,
  `lot_no` VARCHAR(45) NULL,
  `serial_no` VARCHAR(45) NULL,
  `attribute1` VARCHAR(45) NULL,
  `attribute2` VARCHAR(45) NULL,
  `attribute3` VARCHAR(45) NULL,
  `attribute4` INT NULL,
  `attribute5` INT NULL,
  `batch_no` VARCHAR(45) NULL,
  `is_deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sale_order_detail_sale_order1_idx` (`sale_order_id` ASC),
  CONSTRAINT `fk_sale_order_detail_sale_order1`
    FOREIGN KEY (`sale_order_id`)
    REFERENCES `giodis-oms`.`sale_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `giodis-oms`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `giodis-oms`.`report` ;

CREATE TABLE IF NOT EXISTS `giodis-oms`.`report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `report_name` VARCHAR(45) NULL,
  `query` VARCHAR(1000) NULL,
  `status` VARCHAR(45) NULL,
  `field1` VARCHAR(45) NULL,
  `field2` VARCHAR(45) NULL,
  `field3` VARCHAR(45) NULL,
  `field4` INT NULL,
  `field5` INT NULL,
  `is_deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `giodis-oms`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `giodis-oms`.`role` ;

CREATE TABLE IF NOT EXISTS `giodis-oms`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(15) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `is_deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `giodis-oms`.`user_has_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `giodis-oms`.`user_has_role` ;

CREATE TABLE IF NOT EXISTS `giodis-oms`.`user_has_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_role_role1_idx` (`role_id` ASC),
  INDEX `fk_user_has_role_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `giodis-oms`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `giodis-oms`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
